//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaDepartamentoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroVenda
    {
        public int IdProduto { get; set; }
        public int IdVenda { get; set; }
        public int Quantidade { get; set; }
        public double ValorProduto { get; set; }
        public int IdDepartamento { get; set; }
        public int IdVendedor { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Venda Venda { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
