//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaDepartamentoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.Chefias = new HashSet<Chefia>();
            this.RegistroVendas = new HashSet<RegistroVenda>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Rg { get; set; }
        public short Escolaridade { get; set; }
        public bool Desligado { get; set; }
        public System.DateTime DataAdmissao { get; set; }
        public string CPF { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chefia> Chefias { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroVenda> RegistroVendas { get; set; }
    }
}
